import type { Detail } from './site-content';

export const legal: Detail[] = [
  { slug: 'privacy', title: 'Privacy policy', category: 'Legal / Updated 7 September 2026', intro: 'This notice explains how ELEVEN handles information submitted through this website and project enquiry form. Product-specific processing is addressed in the relevant service agreement and privacy information.', sections: [
    { title: 'Who to contact', body: 'ELEVEN operates this website. For questions about this notice, your information or a privacy request, contact hello@elev1.us. The legal contracting entity and its address will be identified in any proposal or agreement before an engagement begins.' },
    { title: 'Information we collect', body: 'The enquiry form collects your name, work email, company or independent status, role, location, project title, requirements, budget range, timeline and selected services. You may also provide a telephone number, website, existing technology, reference links and other context. Hosting and email providers may process technical information such as IP addresses, request times and delivery logs to operate and protect their services. Do not include passwords, payment-card information, identity documents, biometric data or confidential third-party records in an enquiry.' },
    { title: 'How and why we use it', body: 'We use enquiry information to understand your request, assess fit, prepare a response or proposal and communicate about a possible engagement. We also use limited technical information to maintain security, diagnose problems and prevent abuse. Where applicable law requires a lawful basis, processing may be necessary to take steps at your request before a contract, pursue legitimate interests in responding to business enquiries and securing the service, or meet legal obligations. Submitting this form does not subscribe you to marketing.' },
    { title: 'Service providers and international processing', body: 'Project enquiries are sent to our team using Resend when email submission is configured. Our hosting provider, email delivery provider and business email services process information necessary to provide their services. These providers may process data in countries other than your own. Where required, appropriate contractual safeguards must apply to those transfers. We do not sell enquiry information. Information may also be disclosed when legally required or necessary to establish or defend legal claims.' },
    { title: 'Retention and security', body: 'Enquiries are held in our business correspondence for as long as needed to assess and respond to the request, conduct related discussions and maintain relevant engagement records. Retention depends on whether the enquiry becomes a project and any applicable accounting, legal or dispute requirements. You may request deletion of an unneeded enquiry. This form does not store a persistent browser draft or a separate application database record. Access to submitted information should be limited to people who need it for these purposes. No internet transmission or storage system is risk-free.' },
    { title: 'Your choices and rights', body: 'Depending on the law that applies to you, you may request access, correction, deletion, restriction or a portable copy of your personal information, or object to certain processing. Where processing relies on consent, you may withdraw it without affecting earlier lawful processing. Contact hello@elev1.us; we may need proportionate information to verify your request. You may also complain to the relevant data protection authority. Rights and exceptions depend on your jurisdiction.' },
    { title: 'KYC and product data', body: 'This website does not perform identity matching or collect KYC evidence. Any KYC service requires its own documented purposes, allocation of controller and processor responsibilities, lawful basis, security measures, retention rules and notices. Project-enquiry consent does not authorise biometric processing, identity verification or model training.' },
    { title: 'Updates and external sites', body: 'We may update this notice when the website or its processing changes and will revise the date above. External links lead to services with their own notices. This website is intended for business enquiries and is not directed at children.' },
  ] },
  { slug: 'terms', title: 'Terms & conditions', category: 'Legal / Updated 7 September 2026', intro: 'These terms apply to browsing this website and submitting an enquiry. Paid services and product access require a separate agreement.', sections: [
    { title: 'Website use', body: 'Use the website lawfully and provide accurate information that you are authorised to share. You must not interfere with its operation, attempt unauthorised access, distribute malicious code, impersonate another person or use the enquiry form for spam. If you do not agree with these terms, do not use the website.' },
    { title: 'Enquiries and proposals', body: 'Submitting an enquiry does not create a service contract, reserve capacity or commit either party to a project. Scope, deliverables, pricing, taxes, timing, acceptance criteria and the contracting entity are established in a written proposal or agreement. Product descriptions are general information; supported features, destinations, integrations and service levels must be confirmed before purchase.' },
    { title: 'Intellectual property', body: 'Website text, design and original materials are owned by ELEVEN or used with permission, subject to any identified third-party rights. You may view the site and share links for legitimate business purposes. Do not republish or commercially exploit its original materials without permission. Rights to commissioned work, source code and pre-existing materials are set out in the project agreement.' },
    { title: 'Information you submit', body: 'You retain ownership of information you submit and permit us to use it to evaluate and respond to your enquiry. Do not send sensitive personal data, trade secrets or material you are not authorised to disclose. If an NDA is needed, request one before sharing confidential project details.' },
    { title: 'Availability and external services', body: 'We aim to keep the site useful and available but do not promise uninterrupted access or that all information is complete for a particular use. External websites, carriers, payment providers and integrations have their own terms and availability conditions. References to a technology do not imply partnership, endorsement or certification.' },
    { title: 'Responsibility and applicable law', body: 'To the extent permitted by applicable law, general website information is provided without warranties of suitability for a particular purpose. Nothing in these terms excludes liability or rights that cannot lawfully be excluded, including mandatory consumer protections where they apply. Liability allocation, governing law and dispute procedures for paid work are addressed in the signed agreement; these website terms do not replace it.' },
    { title: 'Changes and contact', body: 'We may revise these website terms and update the date above. Changes to an existing project remain governed by its agreement. Questions or concerns can be sent to hello@elev1.us.' },
  ] },
  { slug: 'cookies', title: 'Cookie notice', category: 'Legal / Updated 7 September 2026', intro: 'The website’s current application code does not add advertising cookies, analytics trackers or persistent browser storage for project enquiries.', sections: [
    { title: 'Essential platform functions', body: 'The hosting platform may use essential cookies or similar mechanisms for access control, authentication, security and routing. These are distinct from advertising or audience measurement. Platform behaviour can differ between a restricted preview and a public deployment.' },
    { title: 'Your browser and external services', body: 'You can manage or delete cookies in your browser settings. Blocking essential cookies may affect access to a restricted site. Following an external product or service link takes you to a site with its own cookie practices. Our locally hosted font does not require a request to a third-party font service.' },
    { title: 'Future changes', body: 'If optional analytics or marketing technologies are introduced, this notice should be updated and any legally required consent obtained before those technologies run. Contact hello@elev1.us with questions about the current site.' },
  ] },
  { slug: 'acceptable-use', title: 'Acceptable use', category: 'Legal / Updated 7 September 2026', intro: 'Responsible use protects customers, recipients and the systems they rely on. Product-specific restrictions are also set out in the applicable agreement.', sections: [
    { title: 'Protect systems and other people', body: 'Do not attempt unauthorised access, exploit vulnerabilities, bypass controls, distribute malware, overload services, harvest personal data or misrepresent your identity. Do not submit unlawful, abusive or infringing content. Report a suspected issue privately using the security contact guidance.' },
    { title: 'Messaging and communications', body: 'Do not use communications services for spam, phishing, impersonation, fraudulent messages or unlawful surveillance. Obtain the permissions and contact basis required by applicable law and provider rules. Honour opt-outs, maintain suppression records and comply with destination and sender-registration restrictions.' },
    { title: 'Identity and KYC', body: 'Do not submit another person’s identity data without lawful authority or use matching systems for unlawful discrimination or covert monitoring. Verification workflows require appropriate notices, a lawful processing basis and a way to review disputed or uncertain results. A model score alone must not be represented as conclusive proof of identity.' },
    { title: 'Enforcement and reporting', body: 'We may restrict abusive website traffic. Suspension and termination of paid services are governed by the relevant agreement and applicable law. Send abuse reports to hello@elev1.us with relevant timestamps and identifiers, avoiding unnecessary personal information.' },
  ] },
  { slug: 'security', title: 'Security & disclosure', category: 'Trust', intro: 'Report a suspected security issue directly so it can be assessed with the right context.', sections: [
    { title: 'Report privately', body: 'Email hello@elev1.us with the subject “Security report”. Include the affected URL or product, a concise description, the potential impact and minimal safe steps to reproduce. Do not include credentials, identity documents or customer records. Ask for a suitable transfer method before sharing sensitive evidence.' },
    { title: 'Keep investigation proportionate', body: 'Do not access other people’s data, interrupt services, alter records, perform social engineering or continue testing beyond what is necessary to identify the issue. This page is not authorisation for penetration testing, a safe-harbour commitment or a bug-bounty programme.' },
    { title: 'Security in an engagement', body: 'Project security requirements are agreed according to the data, users and risks involved. They can include access controls, secret handling, auditability, incident procedures, recovery planning and supplier responsibilities. Certifications, penetration-test reports and service commitments should be requested and confirmed directly; this page does not claim any specific certification.' },
  ] },
];
