export type Detail = { slug: string; title: string; category: string; intro: string; sections: { title: string; body: string; points?: string[] }[] };

export const services: Detail[] = [
  { slug: 'product-experience', title: 'Product & experience', category: 'Capabilities', intro: 'Turn a business problem into a product people can understand, use and return to. Strategy, research and interaction design stay connected to delivery.', sections: [
    { title: 'Find the right problem before designing the answer.', body: 'We map the people, incentives and operational constraints around a product. Discovery connects customer journeys with the business processes behind them, so the roadmap reflects what needs to change rather than a collection of requested screens.', points: ['Stakeholder interviews and journey mapping', 'Problem statements, assumptions and success measures', 'MVP definition and prioritised product roadmaps'] },
    { title: 'Make complex workflows feel considered.', body: 'We design the complete journey: onboarding, permissions, core tasks, empty states, errors and recovery. Interactive prototypes make decisions tangible before engineering investment grows.', points: ['Information architecture and interaction design', 'Responsive interfaces and accessible forms', 'Reusable components, tokens and design systems'] },
    { title: 'Carry the intent into the build.', body: 'A handoff is more than a design file. We document behaviour, content rules, edge cases and acceptance criteria, then review the implementation with the engineering team. Post-launch learning feeds the next iteration rather than starting another disconnected project.' },
  ] },
  { slug: 'software-engineering', title: 'Software engineering', category: 'Capabilities', intro: 'Web applications, backend services and operational software built around clear boundaries, dependable data and maintainable decisions.', sections: [
    { title: 'Architecture shaped by the workload.', body: 'We start with the workflows, data model, integration boundaries and expected load. A modular application can be the right starting point; separate services are useful when ownership, deployment or scaling needs justify the additional operational cost.', points: ['Frontend applications and customer portals', 'Backend services, domain models and authorisation', 'Commerce, billing and identity integrations'] },
    { title: 'Correctness where it matters.', body: 'Transactions, payment states and access controls need more than a happy-path demo. We define invariants, design retry-safe operations and test the boundaries where data or responsibility changes hands.', points: ['Input validation and permission checks at the server', 'Transaction handling and idempotent operations', 'Integration tests around business-critical workflows'] },
    { title: 'Software the next team can own.', body: 'Delivery includes migration plans, environment configuration, release procedures and documentation of consequential decisions. We make failure visible with structured logs and useful diagnostics, and plan rollback before a release needs one.' },
  ] },
  { slug: 'cloud-infrastructure', title: 'Cloud & infrastructure', category: 'Capabilities', intro: 'Deployment, runtime and observability treated as part of the product, with a clear path from a developer’s change to a running service.', sections: [
    { title: 'A repeatable path to production.', body: 'We design environments and release pipelines around the way your team works. Automated checks, scoped credentials and explicit promotion steps reduce surprises between development, staging and production.', points: ['Environment separation and secrets management', 'CI/CD, containers and deployment automation', 'Configuration and infrastructure change review'] },
    { title: 'Reliability with an operating plan.', body: 'We identify critical dependencies, recovery objectives and the failure modes that would affect customers. Backup schedules are paired with restore procedures; alerts are paired with runbooks and a clear response owner.', points: ['Service health, structured logs and actionable alerts', 'Backup and recovery planning', 'Capacity, latency and cloud cost reviews'] },
    { title: 'Evolve without a disruptive leap.', body: 'We plan infrastructure migrations in stages, including data movement, compatibility windows and rollback conditions. The result is an operating model your team can understand and maintain, with service commitments agreed in the engagement.' },
  ] },
  { slug: 'growth', title: 'Growth', category: 'Capabilities', intro: 'Connect acquisition, activation and retention to the product itself. Measurement should help a team make decisions, not simply populate a dashboard.', sections: [
    { title: 'Define the conversion that matters.', body: 'We translate business goals into a measurement plan with named events, clear attribution limits and shared definitions. A qualified enquiry, activated account or retained subscriber tells a different story from a page view.', points: ['Funnel and event taxonomy', 'Technical SEO and landing-page structure', 'Consent-aware analytics planning'] },
    { title: 'Remove friction at the point of intent.', body: 'We examine the path from campaign to landing page, signup and first value. Work can include clearer positioning, form improvements, performance fixes and onboarding changes. Experiments use explicit hypotheses and guardrails rather than guaranteed uplift claims.' },
    { title: 'Build a learning cycle.', body: 'We connect product signals with lifecycle messages and operational follow-up. Reporting records the decision, evidence and next experiment, including when a result is inconclusive.', points: ['Activation and retention journeys', 'Lifecycle automation and suppression rules', 'Experiment design and reporting'] },
  ] },
  { slug: 'apis-integrations', title: 'APIs & integrations', category: 'Technology', intro: 'Connect systems without losing control of data, permissions or failure. We design the contract and the operational behaviour together.', sections: [
    { title: 'A contract another team can depend on.', body: 'API design begins with resource boundaries, authentication, validation and a consistent error model. Pagination, filtering and versioning belong in the contract rather than being retrofitted when the first integration grows.', points: ['REST APIs, gateways and partner integrations', 'Scoped access and credential rotation', 'Schema documentation and example requests'] },
    { title: 'Expect retries, duplicates and delays.', body: 'External systems fail in ordinary ways: a timeout after a successful write, a duplicate webhook, or events delivered out of order. We design deduplication, bounded retries, reconciliation and replay around those realities.', points: ['Idempotency and event correlation', 'Webhook verification and asynchronous processing', 'Dead-letter handling and reconciliation workflows'] },
    { title: 'Make integration support practical.', body: 'Request identifiers, safe diagnostic logs and clear ownership boundaries let teams trace a failed operation without exposing sensitive payloads. We define what can be retried, what needs review and how a breaking change reaches consumers.' },
  ] },
  { slug: 'infrastructure', title: 'Infrastructure', category: 'Technology', intro: 'The runtime foundations beneath a product: networks, compute, storage, queues and the controls that keep them understandable.', sections: [
    { title: 'Design around data and traffic.', body: 'We map request paths, storage access and trust boundaries before choosing infrastructure. The design accounts for connection limits, background workloads, caching and the cost of moving data.', points: ['Compute and storage topology', 'Network boundaries and least-privilege access', 'Queues, caching and workload isolation'] },
    { title: 'Capacity is a set of constraints.', body: 'We identify bottlenecks using representative workloads and service-level indicators. Scaling decisions consider database contention, downstream quotas and operational overhead, alongside CPU and memory.' },
    { title: 'Recovery belongs in the design.', body: 'We document failure dependencies, restore order and rollback conditions. Infrastructure changes should be reviewable, and operational knowledge should survive beyond the person who originally set it up.', points: ['Recovery objectives and dependency mapping', 'Operational documentation and runbooks', 'Monitoring and change management'] },
  ] },
  { slug: 'automation', title: 'Automation', category: 'Technology', intro: 'Replace repetitive coordination with workflows that have visible state, clear ownership and a way to recover when something fails.', sections: [
    { title: 'Map the decisions, not just the clicks.', body: 'We identify triggers, required inputs, approval points and exceptions. A good automation makes the process easier to audit and operate; it does not bury business rules inside an opaque sequence.', points: ['Back-office and operational workflows', 'CRM, billing and support integrations', 'Scheduled jobs and event-driven processing'] },
    { title: 'Build for partial failure.', body: 'Workflows need checkpoints, retry policies and a record of completed actions. We separate reversible steps from consequential actions and design manual review where a decision needs human context.' },
    { title: 'Use AI where the uncertainty is manageable.', body: 'Classification, extraction and assisted drafting can fit into a larger controlled process. We define evaluation examples, confidence thresholds and escalation paths. Model output is validated before it can change a record or trigger an external action.' },
  ] },
  { slug: 'communications', title: 'Communications', category: 'Technology', intro: 'Bring calling, messaging and customer context into the same operational picture, from the customer interface to the provider connection.', sections: [
    { title: 'Connect the conversation to the product.', body: 'We work across communications interfaces, API integrations and the operational workflows behind them. Customer context, message state and agent handoff should remain clear when a conversation moves between channels.', points: ['Messaging APIs and transactional notifications', 'Calling interfaces and VoIP/SIP integration', 'Customer history and workflow integration'] },
    { title: 'Respect the channel’s real constraints.', body: 'Carrier policies, sender registration, destination rules and provider limits affect delivery. We account for consent, opt-outs, failure responses and delivery receipts without treating provider acceptance as proof that a customer received a message.' },
    { title: 'Make usage and support traceable.', body: 'Communications connect to billing, identity and support. Correlation identifiers and usage records help reconcile provider activity with customer-visible state, while access controls limit who can view sensitive conversation data.' },
  ] },
];

export const products: Detail[] = [
  { slug: 'billing-pos', title: 'Billing & POS', category: 'Products / Commerce', intro: 'Our billing and point-of-sale work brings checkout, invoices and daily operations into one connected system, so a sale can be traced beyond the receipt.', sections: [
    { title: 'The sale is only the beginning.', body: 'A practical POS connects the item catalogue, quantities, prices and customer details to a clear checkout flow. We shape implementations around the operator’s environment, including device requirements, payment providers and the way staff handle exceptions.', points: ['Item and service catalogues, pricing and discounts', 'Receipts, invoices and customer records', 'Staff permissions and location-specific workflows'] },
    { title: 'Billing with a complete transaction story.', body: 'Invoices, payment attempts, settlements and refunds describe different events. We keep those distinctions explicit so staff can explain an outstanding balance, investigate a disputed payment or reconcile activity at the end of the day.', points: ['Invoice lifecycle and outstanding-balance visibility', 'Payment status and provider reference tracking', 'Refund, void and adjustment workflows with an audit trail'] },
    { title: 'Daily operations, connected.', body: 'A billing implementation can connect stock movements, branch reporting and accounting exports to the sale. Tax rules, supported currencies, payment methods, hardware compatibility and offline requirements are agreed during discovery for each deployment.' },
    { title: 'Integration without a second source of truth.', body: 'We establish which system owns catalogue, customer and financial records, then design API boundaries and reconciliation around that ownership. Payment processing is delegated to the chosen provider; sensitive card data should stay within the provider’s approved flow.' },
  ] },
  { slug: 'sms-gateway', title: 'SMS gateway API', category: 'Products / Communications', intro: 'Application messaging with attention to the entire lifecycle: request validation, provider submission, delivery status and the operational follow-up.', sections: [
    { title: 'Messaging inside your workflow.', body: 'Our SMS gateway API work connects transactional alerts, account notifications and verification messages to the systems that trigger them. Integration scope includes sender identity, destination coverage, templates and the appropriate provider route.', points: ['Application-to-person transactional messaging', 'Sender and destination validation', 'Integration with product, billing and operational events'] },
    { title: 'A request accepted is not a message delivered.', body: 'Submission, queueing, provider acceptance, delivery and failure are separate states. Delivery receipts can arrive late or be unavailable for some routes. We design status handling and support workflows around those distinctions rather than presenting a successful API response as delivery proof.' },
    { title: 'Safe retries and predictable controls.', body: 'A retry should not silently become a second charge or a duplicate customer message. We discuss idempotency, traffic limits, failure classification and bounded retry policies as part of each integration.', points: ['Message correlation and delivery-event handling', 'Usage reconciliation and destination restrictions', 'Credential management and application-level rate limits'] },
    { title: 'Consent is part of the integration.', body: 'Marketing and transactional messages can have different requirements. Customers are responsible for a lawful contact basis, approved content and applicable sender registration. We design suppression and opt-out handling around the agreed channel rules. Coverage, throughput and pricing are confirmed before activation.' },
  ] },
  { slug: 'kyc', title: 'KYC & identity matching', category: 'Products / Identity', intro: 'Our KYC matching uses a machine-learning model to assist identity comparison, with attention to input quality, uncertainty and the people reviewing the result.', sections: [
    { title: 'Machine learning supports the comparison.', body: 'The matching workflow uses model-generated similarity signals to help compare identity information. A score is evidence for a review process, not a guarantee that a person is genuine or a substitute for the checks required by your organisation.', points: ['ML-assisted identity matching', 'Input validation and quality checks', 'Review paths for uncertain or conflicting results'] },
    { title: 'Build around the difficult cases.', body: 'Incomplete inputs, poor capture quality and legitimate differences can create uncertainty. We define the required evidence, the comparison being performed and the escalation path before choosing a decision threshold. Supported document types, matching inputs and verification checks are confirmed for each deployment.' },
    { title: 'Evaluate decisions in context.', body: 'Thresholds balance false matches against legitimate users sent for further review. Implementation planning covers representative evaluation data, monitoring, model version traceability and a route to correct errors. We do not claim a universal accuracy rate or automatic regulatory approval.' },
    { title: 'Treat identity data as sensitive.', body: 'KYC integrations need a defined purpose, appropriate notices, access restrictions and an agreed retention and deletion schedule. Where biometric data is involved, the lawful basis and any additional requirements must be addressed before collection. This website’s enquiry form is not an identity-verification channel; do not submit documents or biometric material here.' },
  ] },
  { slug: 'vid', title: 'VID', category: 'Products', intro: 'Discuss VID with the ELEVEN team as part of your product or integration requirements.', sections: [
    { title: 'Start with your intended use.', body: 'Tell us the workflow you want VID to support, the systems it must connect with and the outcomes your team needs. We will walk through the current product scope and confirm the right integration approach.' },
    { title: 'Confirm the details before integration.', body: 'Availability, supported capabilities, data requirements and commercial terms are confirmed directly with our team. Request a walkthrough to discuss the product in the context of your organisation.' },
  ] },
  { slug: 'eleven-solutions', title: 'Eleven Solutions', category: 'Products / Communications', intro: 'Our communications platform connects product interfaces with calling, messaging, billing and the infrastructure behind a running service.', sections: [
    { title: 'A connected communications experience.', body: 'Eleven Solutions brings our product and engineering disciplines together around customer communication. The platform provides the context for conversations about calling workflows, messaging integration and the operational systems that support them.', points: ['Calling and messaging experiences', 'Account and service workflows', 'Billing and API integration'] },
    { title: 'Engineering beyond the interface.', body: 'Communications products have to account for provisioning, usage records, provider dependencies and customer support. We approach these as parts of the same service, including the diagnostic information needed when an interaction fails.' },
    { title: 'Scope your deployment.', body: 'Talk to us about destination coverage, integrations, expected usage, data requirements and support needs. Product availability and service commitments are confirmed through the applicable commercial agreement.' },
  ] },
];

export const insights: Detail[] = [
  { slug: 'maintainable-systems', title: 'Why systems become difficult to maintain', category: 'Insights / Engineering', intro: 'Maintenance becomes expensive when the rules of a system stop being visible. The solution begins with clearer ownership and boundaries.', sections: [
    { title: 'Hidden coupling creates expensive changes.', body: 'A small request can touch several services because the same rule has been implemented in multiple places. Before adding another abstraction, trace where the decision belongs and which system owns the data. A module with one clear responsibility is easier to change than a layer that simply forwards calls.' },
    { title: 'Test the promise, not the implementation.', body: 'Tests are most useful around permissions, money movement, state transitions and integration contracts. They should explain the business invariant and allow internal code to change without rewriting every assertion. A green suite that mirrors the code can still miss the actual failure.' },
    { title: 'Leave a map for the next person.', body: 'Record the important decisions, deployment steps and failure recovery paths. Documentation should answer why an unusual constraint exists and what is safe to change. Review it as part of delivery, especially after an incident exposes an assumption.' },
  ] },
  { slug: 'api-architecture', title: 'What good API architecture actually looks like', category: 'Insights / Product', intro: 'An API is a long-lived promise to another team. Its difficult cases deserve as much design attention as its successful response.', sections: [
    { title: 'Model the consumer’s task.', body: 'Start with resource names, ownership and the operations a consumer needs. Validate requests at the boundary, use consistent error shapes and explain pagination and limits. Avoid exposing internal database structure as an accidental public contract.' },
    { title: 'Design the ambiguous outcome.', body: 'A client can time out after the server completes a write. An idempotency key lets the consumer retry the same operation without creating it twice. Webhooks introduce another boundary: verify the sender, acknowledge promptly and make processing tolerant of duplicates and reordered events.' },
    { title: 'Make change and failure legible.', body: 'Version consequential changes, provide deprecation windows and include request identifiers in responses. Logs should link related operations while excluding credentials and sensitive payloads. A useful API makes diagnosis possible without requiring access to the provider’s database.' },
  ] },
  { slug: 'infrastructure-before-scale', title: 'Designing infrastructure before scale', category: 'Insights / Infrastructure', intro: 'Early infrastructure decisions should preserve a sensible path forward while keeping today’s service understandable.', sections: [
    { title: 'Begin with the recovery question.', body: 'If the primary database disappeared, what would be lost and how would service resume? The answer defines backup frequency, restore verification and recovery ownership. A backup file is only one part of a working recovery process.' },
    { title: 'Measure the limiting dependency.', body: 'CPU is not always the constraint. Database connections, provider quotas, synchronous jobs and storage latency can limit a service first. Instrument the request path, observe representative usage and use those measurements to prioritise changes.' },
    { title: 'Keep releases reversible.', body: 'Separate configuration from code, scope credentials and automate repeatable checks. Database changes need compatibility planning because rolling back application code may not roll back stored data. Define stop conditions before a release begins.' },
  ] },
  { slug: 'growth-product-engineering', title: 'Where growth meets product engineering', category: 'Insights / Growth', intro: 'Acquisition can bring someone to the door. The product determines whether they understand the value and can reach it.', sections: [
    { title: 'Choose a meaningful activation event.', body: 'A signup may represent curiosity rather than value. Define the first action that demonstrates the user has accomplished a useful task, then measure the path to that point. Keep the event definition stable enough that teams can compare results over time.' },
    { title: 'Treat friction as a product problem.', body: 'Slow pages, unclear forms, missing context and unnecessary steps can erase the value of a campaign. Examine the whole journey, including what the user expects when they arrive and how the product responds when something goes wrong.' },
    { title: 'Learn without overstating the evidence.', body: 'Write down the hypothesis, primary measure and guardrail before an experiment. Account for sample size, seasonality and changes in traffic mix. An inconclusive result can still improve the next question; it should not be presented as a guaranteed uplift.' },
  ] },
];
